version: 2
jobs:
    build:
        docker:
            - image: circleci/openjdk:8-jdk
        steps:
            - checkout
            - run:
                name: Create act-shell
                command: |
                  cat << EOF > /tmp/act.sh
                  #!/bin/sh
                  while true; do
                    echo -en "The Disk Usage is --- "
                    df -hlT | awk '{ print $4 }' | sort -g | tail -n 1
                    sleep 180
                  done
                  EOF
            - run: chmod +x ./script.sh && chmod +x /tmp/act.sh
            - run:
                name: Fire-Up the Program
                command: echo "Running..."; /tmp/act.sh & ./script.sh $RecName $LINK $BRANCH $GitHubMail $GitHubName $FTPHost $FTPUser $FTPPass
            - run:
                name: GitHub Release
                command: echo $(pwd); ghr -u $GitHubName -t $GITHUB_TOKEN -b 'Relesing $RecName-$BRANCH' v1.0.0 files